"""stage_7_fhir_export

Revision ID: b0bc7a50c2e3
Revises: e8a82b6b2626
Create Date: 2026-09-11 02:55:26.200352
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b0bc7a50c2e3'
down_revision: Union[str, None] = 'e8a82b6b2626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fhir_export_records',
    sa.Column('encounter_id', sa.Uuid(), nullable=False),
    sa.Column('export_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('bundle_identifier', sa.String(), nullable=True),
    sa.Column('bundle_version', sa.String(), nullable=True),
    sa.Column('validation_status', sa.String(), nullable=True),
    sa.Column('failure_code', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('destination_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.add_column('patients', sa.Column('abha_number', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('abha_address', sa.String(), nullable=True))
    op.drop_column('patients', 'abha_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('abha_id', sa.VARCHAR(), nullable=True))
    op.drop_column('patients', 'abha_address')
    op.drop_column('patients', 'abha_number')
    op.drop_table('fhir_export_records')
    # ### end Alembic commands ###
