"""stage_6_models

Revision ID: e8a82b6b2626
Revises: e3c358b22656
Create Date: 2026-09-11 02:36:26.761454
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e8a82b6b2626'
down_revision: Union[str, None] = 'e3c358b22656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safety_alerts',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('alert_category', sa.String(), nullable=False),
    sa.Column('deterministic_explanation', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('matched_fact_ids', sa.JSON(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['intake_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinical_conflicts',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('slot', sa.String(), nullable=False),
    sa.Column('fact_id_1', sa.Uuid(), nullable=False),
    sa.Column('fact_id_2', sa.Uuid(), nullable=False),
    sa.Column('relationship_status', sa.String(), nullable=False),
    sa.Column('resolution_notes', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fact_id_1'], ['clinical_answers.id'], ),
    sa.ForeignKeyConstraint(['fact_id_2'], ['clinical_answers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['intake_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clinical_answers', sa.Column('patient_reported_date', sa.String(), nullable=True))
    op.add_column('clinical_answers', sa.Column('relative_duration', sa.String(), nullable=True))
    op.add_column('clinical_answers', sa.Column('is_approximate', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinical_answers', 'is_approximate')
    op.drop_column('clinical_answers', 'relative_duration')
    op.drop_column('clinical_answers', 'patient_reported_date')
    op.drop_table('clinical_conflicts')
    op.drop_table('safety_alerts')
    # ### end Alembic commands ###
