import React from 'react';
import {
  CircleDashed,
  Landmark,
  Accessibility,
  QrCode,
  ContactRound,
  CircleCheck,
  ArrowRight,
  Mic,
  ShieldCheck,
  Camera,
  Upload,
  FileText,
  Clock,
  User,
  HeartPulse,
  Flame,
  Moon,
  ThermometerSun,
  ChevronRight,
  PhoneCall
} from 'lucide-react';

/**
 * Medical Records OCR Camera
 * Generated by Flowstep AI for SwasthyaSaathi Android Mobile App
 * Screen ID: b69e39c4-aa20-42ab-b965-ef8fe1902f77
 */
export const Screen05_DocumentScanner: React.FC = () => {
  return (
    <!-- screenType: "mobile_android" width: "360" height: "780" name: "Screen 5" colorTheme: "orange" screenId: "b69e39c4-aa20-42ab-b965-ef8fe1902f77" -->
    <div className="bg-background text-foreground w-full h-fit">
      <header className="bg-primary text-primary-foreground border-t-border border-r-border border-b border-b-border border-l-border w-full">
        <div className="flex pr-4 pl-4 items-center gap-3 min-h-16">
          <div className="flex items-center flex-1 gap-3 min-w-0">
            <div
              className="rounded-full border-t-2 border-t-primary-foreground/80 border-r-2 border-r-primary-foreground/80 border-b-2 border-b-primary-foreground/80 border-l-2 border-l-primary-foreground/80 flex justify-center items-center shrink-0 size-10"
              aria-label="Ashok Chakra emblem"
            >
              <CircleDashed className="size-7" aria-hidden="true" />
            </div>
            <div className="min-w-0">
              <div className="font-semibold text-ellipsis whitespace-nowrap text-base tracking-tight overflow-hidden">
                SwasthyaSaathi
              </div>
              <div className="whitespace-nowrap text-primary-foreground/80 text-xs leading-tight">
                Health Companion / स्वास्थ्य साथी
              </div>
            </div>
          </div>
          <div className="flex items-center shrink-0 gap-2">
            <div
              className="rounded-md bg-accent text-accent-foreground flex pt-1.5 pr-2 pb-1.5 pl-2 items-center gap-1.5 max-w-32"
              aria-label="Government / AYUSH Hospital"
            >
              <Landmark className="shrink-0 size-4" aria-hidden="true" />
              <span className="font-semibold text-[10px] leading-tight">
                Government / AYUSH Hospital
              </span>
            </div>
            <button
              type="button"
              className="transition-colors rounded-full text-primary-foreground flex justify-center items-center shrink-0 size-12"
              aria-label="Help and accessibility"
            >
              <Accessibility className="size-6" aria-hidden="true" />
            </button>
          </div>
        </div>
      </header>
      <main className="bg-muted flex pt-4 pr-4 pb-4 pl-4 flex-col gap-6">
        <section className="flex flex-col gap-2">
          <h1 className="font-bold text-2xl leading-tight tracking-tight">
            Upload Previous Medical Records / पिछले पर्चे जोड़ें
          </h1>
          <p className="text-muted-foreground text-sm">
            Help your doctor prepare before the consultation.
          </p>
        </section>
        <section className="flex flex-col gap-4">
          <div className="bg-[oklch(0.20_0.04_250)] shadow-[0px_1px_3px_rgba(0,_0,_0,_0.1),_0px_1px_2px_-1px_rgba(0,_0,_0,_0.1)] rounded-2xl flex relative justify-center items-center h-72 overflow-hidden">
            <div className="rounded-lg border-t border-t-primary-foreground/10 border-r border-r-primary-foreground/10 border-b border-b-primary-foreground/10 border-l border-l-primary-foreground/10 absolute top-5 right-5 bottom-5 left-5">
              <div className="rounded-full bg-primary absolute top-0 left-0 w-1 h-7" />
              <div className="rounded-full bg-primary absolute top-0 left-0 w-7 h-1" />
              <div className="rounded-full bg-primary absolute top-0 right-0 w-1 h-7" />
              <div className="rounded-full bg-primary absolute top-0 right-0 w-7 h-1" />
              <div className="rounded-full bg-primary absolute bottom-0 left-0 w-1 h-7" />
              <div className="rounded-full bg-primary absolute bottom-0 left-0 w-7 h-1" />
              <div className="rounded-full bg-primary absolute right-0 bottom-0 w-1 h-7" />
              <div className="rounded-full bg-primary absolute right-0 bottom-0 w-7 h-1" />
              <div className="bg-primary-foreground/30 absolute top-1/2 right-4 left-4 h-px" />
              <div className="-translate-y-1/2 rounded-sm border-t border-t-primary-foreground/80 border-r border-r-primary-foreground/80 border-b border-b-primary-foreground/80 border-l border-l-primary-foreground/80 absolute top-1/2 left-1/2 size-8" />
            </div>
            <div className="bg-[oklch(0.20_0.04_250)]/80 font-medium text-center rounded-full text-primary-foreground text-sm absolute bottom-5 pt-2 pr-4 pb-2 pl-4">
              Align prescription inside the frame
            </div>
          </div>
          <div className="grid gap-3 grid-cols-2">
            <Button className="font-semibold shadow-[0px_1px_3px_rgba(0,_0,_0,_0.1),_0px_1px_2px_-1px_rgba(0,_0,_0,_0.1)] rounded-xl bg-primary text-primary-foreground text-base h-14">
              <Camera className="size-5" />
              Take Photo
            </Button>
            <Button
              variant="outline"
              className="font-semibold text-center rounded-xl text-foreground text-sm border-primary pr-3 pl-3 h-14"
            >
              <Upload className="shrink-0 size-5" />
              Upload from Gallery/PDF
            </Button>
          </div>
        </section>
        <section className="flex flex-col gap-3">
          <h2 className="font-bold text-lg">Scanned documents (1)</h2>
          <Card className="shadow-[0px_1px_3px_rgba(0,_0,_0,_0.1),_0px_1px_2px_-1px_rgba(0,_0,_0,_0.1)] rounded-2xl bg-card border-border pt-3 pr-3 pb-3 pl-3 gap-3">
            <CardContent className="flex pt-0 pr-0 pb-0 pl-0 items-center gap-3">
              <div className="shadow-[inset_0px_2px_4px_rgba(0,_0,_0,_0.05)] rounded-lg bg-[#fffdf7] border-t border-t-border border-r border-r-border border-b border-b-border border-l border-l-border flex pt-2 pr-2 pb-2 pl-2 flex-col shrink-0 gap-1 w-16 h-20 overflow-hidden">
                <div className="font-bold text-slate-700 text-[7px]">
                  Dr. Sharma
                </div>
                <div className="bg-slate-300 w-full h-px" />
                <div className="italic -rotate-4 text-slate-600 text-[8px]">Rx</div>
                <div className="italic rotate-3 text-slate-700 text-[7px]">
                  Tab. Paracetamol
                </div>
                <div className="italic -rotate-3 text-slate-700 text-[7px]">
                  1 - 0 - 1
                </div>
                <div className="-rotate-8 rounded-full border-t border-t-slate-400 border-r border-r-slate-400 border-b border-b-slate-400 border-l border-l-slate-400 mt-1 ml-auto w-5 h-3" />
              </div>
              <div className="flex flex-col flex-1 gap-2 min-w-0">
                <p className="font-semibold text-ellipsis whitespace-nowrap text-sm overflow-hidden">
                  Prescription_12_Jun.pdf
                </p>
                <span className="font-semibold rounded-full bg-emerald-100 text-emerald-700 text-[11px] leading-none pt-1 pr-2 pb-1 pl-2 w-fit">{`Scanning Medicines & Vitals... 100%`}</span>
              </div>
              <CheckCircle2
                className="text-emerald-600 shrink-0 size-6"
                aria-label="Scan complete"
              />
            </CardContent>
          </Card>
          <Button
            variant="link"
            className="font-semibold text-primary text-sm pt-0 pr-0 pb-0 pl-0 self-start h-auto"
          >
            Scan another document
          </Button>
        </section>
      </main>
    </div>;
    
  );
};

export default Screen05_DocumentScanner;
