import React from 'react';
import {
  CircleDashed,
  Landmark,
  Accessibility,
  QrCode,
  ContactRound,
  CircleCheck,
  ArrowRight,
  Mic,
  ShieldCheck,
  Camera,
  Upload,
  FileText,
  Clock,
  User,
  HeartPulse,
  Flame,
  Moon,
  ThermometerSun,
  ChevronRight,
  PhoneCall
} from 'lucide-react';

/**
 * ABHA & Aadhaar Identity Verification
 * Generated by Flowstep AI for SwasthyaSaathi Android Mobile App
 * Screen ID: c8737034-1501-4d35-a262-4a9a28d56070
 */
export const Screen02_AbhaVerification: React.FC = () => {
  return (
    <!-- screenType: "mobile_android" width: "360" height: "780" name: "Screen 2" colorTheme: "orange" screenId: "c8737034-1501-4d35-a262-4a9a28d56070" -->
    <div className="bg-background text-foreground w-full h-fit">
      <header className="bg-primary text-primary-foreground border-t-border border-r-border border-b border-b-border border-l-border w-full">
        <div className="flex pr-4 pl-4 items-center gap-3 min-h-16">
          <div className="flex items-center flex-1 gap-3 min-w-0">
            <div
              className="rounded-full border-t-2 border-t-primary-foreground/80 border-r-2 border-r-primary-foreground/80 border-b-2 border-b-primary-foreground/80 border-l-2 border-l-primary-foreground/80 flex justify-center items-center shrink-0 size-10"
              aria-label="Ashok Chakra emblem"
            >
              <CircleDashed className="size-7" aria-hidden="true" />
            </div>
            <div className="min-w-0">
              <div className="font-semibold text-ellipsis whitespace-nowrap text-base tracking-tight overflow-hidden">
                SwasthyaSaathi
              </div>
              <div className="whitespace-nowrap text-primary-foreground/80 text-xs leading-tight">
                Health Companion / स्वास्थ्य साथी
              </div>
            </div>
          </div>
          <div className="flex items-center shrink-0 gap-2">
            <div
              className="rounded-md bg-accent text-accent-foreground flex pt-1.5 pr-2 pb-1.5 pl-2 items-center gap-1.5 max-w-32"
              aria-label="Government / AYUSH Hospital"
            >
              <Landmark className="shrink-0 size-4" aria-hidden="true" />
              <span className="font-semibold text-[10px] leading-tight">
                Government / AYUSH Hospital
              </span>
            </div>
            <button
              type="button"
              className="transition-colors rounded-full text-primary-foreground flex justify-center items-center shrink-0 size-12"
              aria-label="Help and accessibility"
            >
              <Accessibility className="size-6" aria-hidden="true" />
            </button>
          </div>
        </div>
      </header>
      <main className="bg-muted/70 pt-6 pr-2 pl-2 min-h-[716px]">
        <section className="shadow-[0px_10px_15px_-3px_rgba(0,_0,_0,_0.1),_0px_4px_6px_-4px_rgba(0,_0,_0,_0.1)] rounded-t-3xl bg-card flex pt-6 pr-6 pb-6 pl-6 flex-col gap-6 min-h-[690px]">
          <div
            className="rounded-full bg-muted-foreground/40 mr-auto ml-auto w-12 h-1.5"
            aria-hidden="true"
          />
          <div className="flex flex-col gap-4">
            <div className="flex flex-col gap-1">
              <h1 className="font-semibold text-xl leading-tight">
                Verify your identity / पहचान सत्यापित करें
              </h1>
              <div className="font-medium text-emerald-700 text-sm flex items-center gap-2">
                <ShieldCheck className="size-5" aria-hidden="true" />
                <span>Ayushman Bharat Digital Mission</span>
              </div>
              <p className="text-muted-foreground text-sm leading-5">
                Securely link your visit to your ABHA health records.
              </p>
            </div>
            <div
              className="rounded-xl bg-muted flex pt-1 pr-1 pb-1 pl-1 gap-2"
              role="tablist"
              aria-label="Identity method"
            >
              <button
                type="button"
                role="tab"
                className="font-semibold rounded-lg text-sm pt-2.5 pr-3 pb-2.5 pl-3 flex-1"
              >
                ABHA ID
              </button>
              <button
                type="button"
                role="tab"
                className="font-semibold rounded-lg text-sm pt-2.5 pr-3 pb-2.5 pl-3 flex-1"
              >
                Mobile number
              </button>
            </div>
            <div className="flex flex-col gap-2">
              <label htmlFor="abha-id" className="font-medium text-base">
                14-digit ABHA ID
              </label>
              <input
                id="abha-id"
                type="text"
                inputMode="numeric"
                placeholder="12-3456-7890-1234"
                className="rounded-lg bg-background text-base border-t border-t-input border-r border-r-input border-b border-b-input border-l border-l-input outline-none pr-3 pl-3 h-12"
                defaultValue=""
              />
              <p className="text-muted-foreground text-sm">
                Or use your 10-digit mobile number
              </p>
            </div>
            <button
              type="button"
              className="font-semibold transition-colors shadow-[0px_1px_3px_rgba(0,_0,_0,_0.1),_0px_1px_2px_-1px_rgba(0,_0,_0,_0.1)] rounded-lg bg-primary text-primary-foreground text-base pr-4 pl-4 h-12"
            >
              Send OTP / OTP भेजें
            </button>
          </div>
          <div className="border-x-border border-t border-t-border border-b-border flex pt-5 flex-col gap-3">
            <label className="font-medium text-base">Enter 6-digit OTP</label>
            <div className="flex gap-2">
              <input
                aria-label="OTP digit 1"
                maxLength="1"
                className="font-semibold text-center rounded-lg bg-background text-lg border-t border-t-input border-r border-r-input border-b border-b-input border-l border-l-input outline-none flex-1 h-12 min-w-0"
                defaultValue="4"
              />
              <input
                aria-label="OTP digit 2"
                maxLength="1"
                className="font-semibold text-center rounded-lg bg-background text-lg border-t border-t-input border-r border-r-input border-b border-b-input border-l border-l-input outline-none flex-1 h-12 min-w-0"
                defaultValue="8"
              />
              <input
                aria-label="OTP digit 3"
                maxLength="1"
                className="font-semibold text-center rounded-lg bg-background text-lg border-t border-t-input border-r border-r-input border-b border-b-input border-l border-l-input outline-none flex-1 h-12 min-w-0"
                defaultValue="2"
              />
              <input
                aria-label="OTP digit 4"
                maxLength="1"
                className="font-semibold text-center rounded-lg bg-background text-lg border-t border-t-input border-r border-r-input border-b border-b-input border-l border-l-input outline-none flex-1 h-12 min-w-0"
                defaultValue="1"
              />
              <input
                aria-label="OTP digit 5"
                maxLength="1"
                className="font-semibold text-center rounded-lg bg-background text-lg border-t border-t-input border-r border-r-input border-b border-b-input border-l border-l-input outline-none flex-1 h-12 min-w-0"
                defaultValue="0"
              />
              <input
                aria-label="OTP digit 6"
                maxLength="1"
                className="font-semibold text-center rounded-lg bg-background text-lg border-t border-t-input border-r border-r-input border-b border-b-input border-l border-l-input outline-none flex-1 h-12 min-w-0"
                defaultValue="6"
              />
            </div>
            <div className="text-sm flex justify-between items-center">
              <span className="text-muted-foreground">Resend OTP in 00:24</span>
              <button
                type="button"
                className="underline-offset-4 font-semibold text-primary"
              >
                Change number
              </button>
            </div>
          </div>
          <div className="rounded-xl bg-emerald-50 border-t border-t-emerald-200 border-r border-r-emerald-200 border-b border-b-emerald-200 border-l border-l-emerald-200 flex pt-4 pr-4 pb-4 pl-4 items-center gap-3">
            <div
              className="font-bold rounded-full bg-emerald-100 text-emerald-800 text-base flex justify-center items-center shrink-0 size-12"
              aria-label="Patient initials"
            >
              RS
            </div>
            <div className="flex flex-col flex-1 gap-1 min-w-0">
              <div className="font-semibold text-base">Rahul Sharma</div>
              <div className="text-muted-foreground text-sm">Male • 34 years</div>
              <div className="text-muted-foreground text-sm">
                ABHA Address: rahul@sbx
              </div>
              <div className="font-semibold text-emerald-700 text-xs flex mt-1 items-center gap-1.5">
                <CircleCheck className="size-4" aria-hidden="true" />
                <span>ABDM Verified via Aadhaar OTP</span>
              </div>
            </div>
          </div>
          <button
            type="button"
            className="font-semibold rounded-lg text-base mt-auto pr-4 pl-4 h-12"
          >
            Continue / आगे बढ़ें
          </button>
        </section>
      </main>
    </div>;
    
  );
};

export default Screen02_AbhaVerification;
