import React from 'react';
import {
  CircleDashed,
  Landmark,
  Accessibility,
  QrCode,
  ContactRound,
  CircleCheck,
  ArrowRight,
  Mic,
  ShieldCheck,
  Camera,
  Upload,
  FileText,
  Clock,
  User,
  HeartPulse,
  Flame,
  Moon,
  ThermometerSun,
  ChevronRight,
  PhoneCall
} from 'lucide-react';

/**
 * Summary Review & ABDM Consent
 * Generated by Flowstep AI for SwasthyaSaathi Android Mobile App
 * Screen ID: 4d1a69aa-1656-4f1f-8dc7-d171458e0aa7
 */
export const Screen06_ReviewConsent: React.FC = () => {
  return (
    <!-- screenType: "mobile_android" width: "360" height: "780" name: "Screen 6" colorTheme: "orange" screenId: "4d1a69aa-1656-4f1f-8dc7-d171458e0aa7" -->
    <div className="bg-background text-foreground w-full h-fit">
      <div className="bg-background flex flex-col min-h-[780px]">
        <header className="bg-primary text-primary-foreground border-t-border border-r-border border-b border-b-border border-l-border w-full">
          <div className="flex pr-4 pl-4 items-center gap-3 min-h-16">
            <div className="flex items-center flex-1 gap-3 min-w-0">
              <div
                className="rounded-full border-t-2 border-t-primary-foreground/80 border-r-2 border-r-primary-foreground/80 border-b-2 border-b-primary-foreground/80 border-l-2 border-l-primary-foreground/80 flex justify-center items-center shrink-0 size-10"
                aria-label="Ashok Chakra emblem"
              >
                <CircleDashed className="size-7" aria-hidden="true" />
              </div>
              <div className="min-w-0">
                <div className="font-semibold text-ellipsis whitespace-nowrap text-base tracking-tight overflow-hidden">
                  SwasthyaSaathi
                </div>
                <div className="whitespace-nowrap text-primary-foreground/80 text-xs leading-tight">
                  Health Companion / स्वास्थ्य साथी
                </div>
              </div>
            </div>
            <div className="flex items-center shrink-0 gap-2">
              <div
                className="rounded-md bg-accent text-accent-foreground flex pt-1.5 pr-2 pb-1.5 pl-2 items-center gap-1.5 max-w-32"
                aria-label="Government / AYUSH Hospital"
              >
                <Landmark className="shrink-0 size-4" aria-hidden="true" />
                <span className="font-semibold text-[10px] leading-tight">
                  Government / AYUSH Hospital
                </span>
              </div>
              <button
                type="button"
                className="transition-colors rounded-full text-primary-foreground flex justify-center items-center shrink-0 size-12"
                aria-label="Help and accessibility"
              >
                <Accessibility className="size-6" aria-hidden="true" />
              </button>
            </div>
          </div>
        </header>
        <main className="pt-4 pr-4 pb-4 pl-4 flex-1">
          <section className="mb-6">
            <h1 className="font-semibold text-foreground text-2xl leading-tight mb-2">
              Review your intake / अपनी जानकारी देखें
            </h1>
            <p className="text-muted-foreground text-base leading-6">
              Please check these details before sending them to your doctor.
            </p>
          </section>
          <div
            className="font-medium rounded-lg bg-green-50 text-green-800 text-base border-t border-t-green-200 border-r border-r-green-200 border-b border-b-green-200 border-l border-l-green-200 flex mb-6 pt-4 pr-4 pb-4 pl-4 items-center gap-3"
            role="status"
          >
            <CircleCheck
              className="text-green-700 shrink-0 size-5"
              aria-hidden="true"
            />
            <span>Identity verified with ABHA</span>
          </div>
          <Card className="shadow-[0px_1px_3px_rgba(0,_0,_0,_0.1),_0px_1px_2px_-1px_rgba(0,_0,_0,_0.1)] bg-card border-border mb-6 pt-4 pr-4 pb-4 pl-4 gap-4">
            <CardContent className="pt-0 pr-0 pb-0 pl-0">
              <div className="border-t-border border-r-border border-b border-b-border border-l-border flex mb-0 pt-0 pb-4 gap-3">
                <HeartPulse
                  className="text-primary mt-1 shrink-0 size-5"
                  aria-hidden="true"
                />
                <div className="flex-1 min-w-0">
                  <div className="font-semibold text-foreground text-base mb-1">
                    Chief Complaint / मुख्य समस्या
                  </div>
                  <div className="text-foreground text-base leading-6 mb-1">
                    Stomach pain and burning after meals
                  </div>
                  <div className="font-medium text-green-700 text-sm">
                    Verified from patient voice
                  </div>
                </div>
              </div>
              <div className="border-t-border border-r-border border-b border-b-border border-l-border flex mb-0 pt-4 pb-4 gap-3">
                <Clock3
                  className="text-primary mt-1 shrink-0 size-5"
                  aria-hidden="true"
                />
                <div className="flex-1 min-w-0">
                  <div className="font-semibold text-foreground text-base mb-1">{`Duration & Severity`}</div>
                  <div className="text-foreground text-base leading-6">
                    2 weeks • Moderate
                  </div>
                </div>
              </div>
              <div className="border-t-border border-r-border border-b border-b-border border-l-border flex mb-0 pt-4 pb-4 gap-3">
                <Leaf
                  className="text-primary mt-1 shrink-0 size-5"
                  aria-hidden="true"
                />
                <div className="flex-1 min-w-0">
                  <div className="font-semibold text-foreground text-base mb-1">
                    AYUSH Markers / आयुष संकेतक
                  </div>
                  <div className="text-foreground text-base leading-6 mb-1">{`Agni: Acidity & Burning`}</div>
                  <div className="text-foreground text-base leading-6">
                    Nidra: Sound uninterrupted
                  </div>
                </div>
              </div>
              <div className="flex pt-4 pb-0 gap-3">
                <FileText
                  className="text-primary mt-1 shrink-0 size-5"
                  aria-hidden="true"
                />
                <div className="flex-1 min-w-0">
                  <div className="font-semibold text-foreground text-base mb-1">
                    Attached Documents
                  </div>
                  <div className="text-foreground text-base leading-6 flex items-center gap-2">
                    <span>1 Prescription</span>
                    <CircleCheck
                      className="text-green-700 size-5"
                      aria-label="OCR verified"
                    />
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
          <button
            type="button"
            className="font-medium transition-colors rounded-md text-primary text-base border-t border-t-primary border-r border-r-primary border-b border-b-primary border-l border-l-primary inline-flex mb-6 pt-2.5 pr-4 pb-2.5 pl-4 items-center gap-2"
          >
            <Pencil className="size-4" aria-hidden="true" />
            <span>Edit intake</span>
          </button>
          <div className="flex mb-6 pb-4 items-start gap-3">
            <Checkbox
              className="mt-0.5 size-6"
              id="consent"
              defaultChecked={false}
            />
            <label
              htmlFor="consent"
              className="text-foreground text-base leading-6"
            >
              I consent to share this intake summary with my attending doctor under
              ABDM digital health standards.
            </label>
          </div>
          <p className="text-muted-foreground text-sm">
            Only your care team can access this summary.
          </p>
        </main>
        <div className="bg-card border-x-border border-t border-t-border border-b-border sticky bottom-0 pt-4 pr-4 pb-4 pl-4">
          <Button
            type="button"
            className="font-semibold bg-primary text-primary-foreground text-base gap-2 w-full h-12"
          >
            <Send className="size-5" aria-hidden="true" />
            <span>Submit to Doctor’s Queue / डॉक्टर को भेजें</span>
          </Button>
        </div>
      </div>
    </div>;
    
  );
};

export default Screen06_ReviewConsent;
