import React from 'react';
import {
  CircleDashed,
  Landmark,
  Accessibility,
  QrCode,
  ContactRound,
  CircleCheck,
  ArrowRight,
  Mic,
  ShieldCheck,
  Camera,
  Upload,
  FileText,
  Clock,
  User,
  HeartPulse,
  Flame,
  Moon,
  ThermometerSun,
  ChevronRight,
  PhoneCall
} from 'lucide-react';

/**
 * Multilingual Voice Case Taking
 * Generated by Flowstep AI for SwasthyaSaathi Android Mobile App
 * Screen ID: 87c76027-8e3b-4c13-a736-ca9879e1d33f
 */
export const Screen03_VoiceIntake: React.FC = () => {
  return (
    <!-- screenType: "mobile_android" width: "360" height: "780" name: "Screen 3" colorTheme: "orange" screenId: "87c76027-8e3b-4c13-a736-ca9879e1d33f" -->
    <div className="bg-background text-foreground w-full h-fit">
      <div className="bg-[#faf9f6] flex mr-auto ml-auto flex-col w-full min-h-[780px] max-w-[360px]">
        <header className="bg-primary text-primary-foreground w-full">
          <div className="flex pr-4 pl-4 items-center gap-2 min-h-16">
            <div className="flex items-center flex-1 gap-2 min-w-0">
              <div
                className="rounded-full border-t-2 border-t-primary-foreground/80 border-r-2 border-r-primary-foreground/80 border-b-2 border-b-primary-foreground/80 border-l-2 border-l-primary-foreground/80 flex justify-center items-center shrink-0 size-10"
                aria-label="Ashok Chakra emblem"
              >
                <CircleDashed className="size-7" aria-hidden="true" />
              </div>
              <div className="flex-1 min-w-0">
                <div className="font-semibold whitespace-nowrap text-[13px] tracking-tight">
                  SwasthyaSaathi
                </div>
                <div className="whitespace-nowrap text-primary-foreground/80 text-[11px] leading-tight">
                  Health Companion / स्वास्थ्य साथी
                </div>
              </div>
            </div>
            <div className="flex items-center shrink-0 gap-1">
              <div
                className="rounded-sm bg-accent text-accent-foreground flex pt-1.5 pr-2 pb-1.5 pl-2 items-center gap-1 min-h-10 max-w-[118px]"
                aria-label="Government / AYUSH Hospital"
              >
                <Landmark className="shrink-0 size-3.5" aria-hidden="true" />
                <span className="font-semibold text-center text-[9px] leading-tight">
                  Government / AYUSH Hospital
                </span>
              </div>
              <button
                type="button"
                className="rounded-full text-primary-foreground flex justify-center items-center shrink-0 size-9"
                aria-label="Help and accessibility"
              >
                <Accessibility className="size-5" aria-hidden="true" />
              </button>
            </div>
          </div>
        </header>
        <main className="pt-5 pr-4 pb-28 pl-4 flex-1 overflow-y-auto">
          <section className="mb-5" aria-label="Clinical intake progress">
            <div className="flex mb-3 justify-between items-end gap-2">
              <div>
                <p className="font-bold text-[#14213d] text-lg leading-tight">
                  Step 1 of 5
                </p>
                <p className="font-medium text-muted-foreground text-sm leading-tight mt-1">
                  चरण 1 में 5
                </p>
              </div>
              <span className="font-bold text-primary text-sm">20%</span>
            </div>
            <div
              className="rounded-full bg-secondary mb-3 h-2 overflow-hidden"
              aria-label="20 percent complete"
            >
              <div className="rounded-full bg-primary w-1/5 h-full" />
            </div>
            <div className="font-semibold text-center text-[12px] leading-tight grid gap-2 grid-cols-5">
              <div className="text-primary">
                Chief
                <br />
                Complaint
              </div>
              <div className="text-muted-foreground">Duration</div>
              <div className="text-muted-foreground">Severity</div>
              <div className="text-muted-foreground">
                Past
                <br />
                History
              </div>
              <div className="text-muted-foreground">
                AYUSH
                <br />
                Markers
              </div>
            </div>
          </section>
          <Card className="shadow-[0px_1px_3px_rgba(0,_0,_0,_0.08)] rounded-xl bg-card border-border pt-4 pr-4 pb-4 pl-4 gap-5">
            <CardHeader className="pt-0 pr-0 pb-0 pl-0 gap-2">
              <CardTitle className="font-bold text-[#14213d] text-xl leading-snug">
                What health problems are you experiencing today? / आज आपको क्या
                समस्या है?
              </CardTitle>
              <CardDescription className="text-muted-foreground text-base leading-relaxed">
                You can speak in Hindi or English.
              </CardDescription>
            </CardHeader>
            <CardContent className="pt-0 pr-0 pb-0 pl-0">
              <div className="flex mb-5 pt-2 pb-1 flex-col items-center gap-3">
                <div className="flex relative justify-center items-center size-36">
                  <div className="rounded-full border-t-2 border-t-primary/25 border-r-2 border-r-primary/25 border-b-2 border-b-primary/25 border-l-2 border-l-primary/25 absolute size-36" />
                  <div className="rounded-full border-t-2 border-t-[#3f7d58]/50 border-r-2 border-r-[#3f7d58]/50 border-b-2 border-b-[#3f7d58]/50 border-l-2 border-l-[#3f7d58]/50 absolute size-28" />
                  <Button
                    type="button"
                    className="shadow-[0px_8px_16px_-4px_rgba(0,_0,_0,_0.2)] rounded-full bg-primary text-primary-foreground relative z-10 size-24"
                    aria-label="Tap to speak"
                  >
                    <Mic className="size-10" />
                  </Button>
                </div>
                <p className="font-semibold text-center text-[#14213d] text-base">
                  Tap to Speak in Hindi or English
                </p>
              </div>
              <div
                className="flex mb-5 pb-1 gap-2 overflow-x-auto"
                aria-label="Common health problems"
              >
                <Button
                  type="button"
                  variant="outline"
                  className="text-left rounded-full text-[#14213d] text-sm border-border pr-3 pl-3 shrink-0 min-h-11"
                >{`Stomach Pain & Burning`}</Button>
                <Button
                  type="button"
                  variant="outline"
                  className="text-left rounded-full text-[#14213d] text-sm border-border pr-3 pl-3 shrink-0 min-h-11"
                >
                  Joint Stiffness
                </Button>
                <Button
                  type="button"
                  variant="outline"
                  className="text-left rounded-full text-[#14213d] text-sm border-border pr-3 pl-3 shrink-0 min-h-11"
                >
                  Acidity / Heartburn
                </Button>
                <Button
                  type="button"
                  variant="outline"
                  className="text-left rounded-full text-[#14213d] text-sm border-border pr-3 pl-3 shrink-0 min-h-11"
                >
                  Chronic Cough
                </Button>
              </div>
              <div>
                <Label
                  htmlFor="health-words"
                  className="font-semibold text-[#14213d] text-base mb-2"
                >
                  Your words / आपकी बात
                </Label>
                <Textarea
                  id="health-words"
                  className="resize-none rounded-lg bg-background text-base leading-relaxed border-t border-t-input border-r border-r-input border-b border-b-input border-l border-l-input mb-2 pt-3 pr-3 pb-3 pl-3 min-h-28"
                  defaultValue="I have stomach pain and burning after meals for two weeks."
                />
                <div className="font-semibold rounded-full bg-[#e7f3e9] text-[#3f7d58] text-sm inline-flex pt-1 pr-2.5 pb-1 pl-2.5 items-center gap-1">
                  <span>✓ AI Transcribed</span>
                </div>
              </div>
            </CardContent>
          </Card>
        </main>
        <div className="-translate-x-1/2 bg-background border-x-border border-t border-t-border border-b-border flex fixed bottom-0 left-1/2 pt-4 pr-4 pb-4 pl-4 justify-between items-center gap-3 w-full max-w-[360px]">
          <Button
            type="button"
            variant="ghost"
            className="font-semibold rounded-lg text-[#14213d] text-base pr-4 pl-4 min-h-12"
          >
            Previous
          </Button>
          <Button
            type="button"
            className="font-bold rounded-lg bg-primary text-primary-foreground text-base pr-4 pl-4 flex-1 min-h-12"
          >
            Continue / आगे बढ़ें
            <ArrowRight className="ml-2 size-5" />
          </Button>
        </div>
      </div>
    </div>;
    
  );
};

export default Screen03_VoiceIntake;
