import React from 'react';
import {
  CircleDashed,
  Landmark,
  Accessibility,
  QrCode,
  ContactRound,
  CircleCheck,
  ArrowRight,
  Mic,
  ShieldCheck,
  Camera,
  Upload,
  FileText,
  Clock,
  User,
  HeartPulse,
  Flame,
  Moon,
  ThermometerSun,
  ChevronRight,
  PhoneCall
} from 'lucide-react';

/**
 * Welcome & Language Selection
 * Generated by Flowstep AI for SwasthyaSaathi Android Mobile App
 * Screen ID: d689769b-8555-4f2b-ae57-e78e481daae9
 */
export const Screen01_Welcome: React.FC = () => {
  return (
    <!-- screenType: "mobile_android" width: "360" height: "780" name: "Screen 1" colorTheme: "default" screenId: "d689769b-8555-4f2b-ae57-e78e481daae9" -->
    <div className="bg-background text-foreground w-full h-fit">
      <header className="bg-card text-slate-900 border-t-orange-500 border-r-orange-500 border-b-4 border-b-orange-500 border-l-orange-500 w-full">
        <div className="flex pr-4 pl-4 items-center gap-2 min-h-20">
          <div
            className="rounded-2xl text-orange-600 border-t-2 border-t-orange-500 border-r-2 border-r-orange-500 border-b-2 border-b-orange-500 border-l-2 border-l-orange-500 flex justify-center items-center shrink-0 size-11"
            aria-label="Ashok Chakra emblem"
          >
            <CircleDashed className="size-7" aria-hidden="true" />
          </div>
          <div className="flex-1 min-w-0">
            <div className="font-bold text-ellipsis whitespace-nowrap text-sm tracking-tight overflow-hidden">
              SwasthyaSaathi
            </div>
            <div className="text-ellipsis whitespace-nowrap text-slate-500 text-[10px] overflow-hidden">
              Health Companion / स्वास्थ्य साथी
            </div>
          </div>
          <div className="flex items-center shrink-0 gap-1">
            <div
              className="rounded-xl bg-slate-50 text-slate-800 border-t border-t-slate-200 border-r border-r-slate-200 border-b border-b-slate-200 border-l border-l-slate-200 flex pt-1.5 pr-2 pb-1.5 pl-2 items-center gap-1 max-w-28"
              aria-label="Government / AYUSH Hospital"
            >
              <Landmark className="shrink-0 size-4" aria-hidden="true" />
              <span className="font-bold text-[9px] leading-tight">
                Government / AYUSH Hospital
              </span>
            </div>
            <button
              type="button"
              className="rounded-xl text-slate-700 flex justify-center items-center size-10"
              aria-label="Help and accessibility"
            >
              <Accessibility className="size-6" aria-hidden="true" />
            </button>
          </div>
        </div>
      </header>
      <main className="bg-stone-50 flex pt-8 pr-4 pb-6 pl-4 flex-col gap-6 min-h-[700px]">
        <section className="flex flex-col gap-2" aria-labelledby="welcome-heading">
          <h1
            id="welcome-heading"
            className="font-extrabold text-slate-950 text-3xl tracking-tight"
          >
            Namaste / नमस्ते
          </h1>
          <p className="text-slate-700 text-base leading-6">
            Begin your secure pre-consultation journey.
          </p>
        </section>
        <div
          className="flex pb-1 gap-2 overflow-x-auto"
          aria-label="Choose language"
        >
          <button type="button">Hindi (हिंदी)</button>
          <button type="button">English</button>
          <button type="button">Marathi</button>
          <button type="button">Bengali</button>
          <button type="button">Tamil</button>
          <button type="button">Telugu</button>
        </div>
        <section
          className="flex flex-col gap-4"
          aria-labelledby="quick-start-heading"
        >
          <h2
            id="quick-start-heading"
            className="font-extrabold text-slate-950 text-xl"
          >
            Quick start / तुरंत शुरू करें
          </h2>
          <button type="button">
            <div className="rounded-2xl bg-orange-100 text-orange-700 flex justify-center items-center shrink-0 size-14">
              <QrCode className="size-8" aria-hidden="true" />
            </div>
            <div className="text-left flex flex-col flex-1 gap-1 min-w-0">
              <span className="font-bold text-slate-950 text-lg leading-6">
                Scan OPD Reception QR Code
              </span>
              <span className="text-slate-600 text-base leading-6">
                Fast check-in at your hospital reception
              </span>
            </div>
          </button>
          <button type="button">
            <div className="rounded-2xl bg-slate-100 text-slate-800 flex justify-center items-center shrink-0 size-14">
              <ContactRound className="size-8" aria-hidden="true" />
            </div>
            <div className="text-left flex flex-col flex-1 gap-1 min-w-0">
              <span className="font-bold text-slate-950 text-lg leading-6">
                Check-in with ABHA Number
              </span>
              <span className="text-slate-600 text-base leading-6">
                Use your 14-digit Ayushman Bharat Health Account
              </span>
            </div>
          </button>
        </section>
        <div className="text-emerald-700 text-base leading-6 flex items-start gap-2">
          <CircleCheck className="mt-0.5 shrink-0 size-5" aria-hidden="true" />
          <span>Your health information stays secure under ABDM standards.</span>
        </div>
        <div className="flex pt-2 flex-col gap-4">
          <button
            type="button"
            className="font-extrabold text-center shadow-[0px_10px_15px_-3px_#ffd6a7,_0px_4px_6px_-4px_#ffd6a7] rounded-2xl bg-orange-600 text-white text-base flex pt-4 pr-4 pb-4 pl-4 justify-center items-center gap-2 w-full min-h-14"
          >
            <span>Start Pre-Consultation Intake / परामर्श शुरू करें</span>
            <ArrowRight className="shrink-0 size-5" aria-hidden="true" />
          </button>
          <a
            href="#help-desk"
            className="underline underline-offset-4 font-medium text-center text-slate-700 text-base"
          >
            Emergency? Call hospital help desk
          </a>
        </div>
      </main>
    </div>;
    
  );
};

export default Screen01_Welcome;
