import React from 'react';
import {
  CircleDashed,
  Landmark,
  Accessibility,
  QrCode,
  ContactRound,
  CircleCheck,
  ArrowRight,
  Mic,
  ShieldCheck,
  Camera,
  Upload,
  FileText,
  Clock,
  User,
  HeartPulse,
  Flame,
  Moon,
  ThermometerSun,
  ChevronRight,
  PhoneCall
} from 'lucide-react';

/**
 * AYUSH Prakriti & Clinical Markers
 * Generated by Flowstep AI for SwasthyaSaathi Android Mobile App
 * Screen ID: f673357b-9c0c-49bb-9ef9-7e73859a3dca
 */
export const Screen04_AyushProfile: React.FC = () => {
  return (
    <!-- screenType: "mobile_android" width: "360" height: "780" name: "Screen 4" colorTheme: "orange" screenId: "f673357b-9c0c-49bb-9ef9-7e73859a3dca" -->
    <div className="bg-background text-foreground w-full h-fit">
      <header className="bg-primary text-primary-foreground border-b border-b-border w-full">
        <div className="flex pr-3 pl-3 items-center gap-2 min-h-16">
          <div className="flex items-center flex-1 gap-2 min-w-0">
            <div
              className="rounded-full border-t-2 border-t-primary-foreground/80 border-r-2 border-r-primary-foreground/80 border-b-2 border-b-primary-foreground/80 border-l-2 border-l-primary-foreground/80 flex justify-center items-center shrink-0 size-9"
              aria-label="Ashok Chakra emblem"
            >
              <CircleDashed className="size-6" aria-hidden="true" />
            </div>
            <div className="flex-1 min-w-0">
              <div className="font-semibold text-ellipsis whitespace-nowrap text-sm tracking-tight overflow-hidden">
                SwasthyaSaathi
              </div>
              <div className="text-ellipsis whitespace-nowrap text-primary-foreground/80 text-[11px] leading-tight overflow-hidden">
                Health Companion / स्वास्थ्य साथी
              </div>
            </div>
          </div>
          <div className="flex items-center shrink-0 gap-1">
            <div
              className="rounded-md bg-accent text-accent-foreground flex pt-1.5 pr-1.5 pb-1.5 pl-1.5 justify-center items-center gap-1 w-28"
              aria-label="Government / AYUSH Hospital"
            >
              <Landmark className="shrink-0 size-3.5" aria-hidden="true" />
              <span className="font-semibold text-center text-[9px] leading-tight">
                Government / AYUSH Hospital
              </span>
            </div>
            <button
              type="button"
              className="rounded-full text-primary-foreground flex justify-center items-center shrink-0 size-10"
              aria-label="Help and accessibility"
            >
              <Accessibility className="size-5" aria-hidden="true" />
            </button>
          </div>
        </div>
      </header>
      <main className="flex pt-6 pr-4 pb-32 pl-4 flex-col flex-1 gap-6">
        <section className="flex flex-col gap-2">
          <h1 className="font-semibold text-2xl leading-tight tracking-tight">
            Your AYUSH profile / आपका आयुष प्रोफ़ाइल
          </h1>
          <p className="text-muted-foreground text-sm leading-relaxed">
            These questions help your doctor understand your natural patterns.
          </p>
        </section>
        <section className="flex flex-col gap-2" aria-label="Assessment progress">
          <div className="font-medium text-sm flex justify-between items-center">
            <span>Step 5 of 5 / चरण 5 में 5</span>
          </div>
          <div className="rounded-full bg-muted w-full h-2 overflow-hidden">
            <div className="rounded-full bg-primary size-full" />
          </div>
        </section>
        <div className="flex flex-col gap-4">
          <Card className="shadow-[0px_1px_3px_rgba(0,_0,_0,_0.1),_0px_1px_2px_-1px_rgba(0,_0,_0,_0.1)] rounded-xl bg-card border-border pt-4 pr-4 pb-4 pl-4 gap-4">
            <CardHeader className="pt-0 pr-0 pb-0 pl-0 gap-3">
              <div className="flex items-start gap-3">
                <div className="rounded-lg bg-secondary text-secondary-foreground flex justify-center items-center shrink-0 size-10">
                  <Utensils className="size-5" aria-hidden="true" />
                </div>
                <div className="flex-1 min-w-0">
                  <CardTitle className="text-base leading-tight">{`Digestion & Appetite / पाचन और भूख`}</CardTitle>
                  <div className="font-medium uppercase text-muted-foreground text-xs tracking-wider mt-1">
                    Agni
                  </div>
                </div>
              </div>
            </CardHeader>
            <CardContent className="grid pt-0 pr-0 pb-0 pl-0 gap-2">
              <button type="button">
                <CircleDot
                  className="text-muted-foreground shrink-0 size-5"
                  aria-hidden="true"
                />
                <span className="font-medium text-sm flex-1">Normal</span>
                <Check
                  className="text-primary hidden shrink-0 size-5"
                  aria-hidden="true"
                />
              </button>
              <button type="button">
                <Gauge
                  className="text-muted-foreground shrink-0 size-5"
                  aria-hidden="true"
                />
                <span className="font-medium text-sm flex-1">Sluggish / Low</span>
                <Check
                  className="text-primary hidden shrink-0 size-5"
                  aria-hidden="true"
                />
              </button>
              <button type="button">
                <Flame
                  className="text-muted-foreground shrink-0 size-5"
                  aria-hidden="true"
                />
                <span className="font-medium text-sm flex-1">{`Acidity & Burning`}</span>
                <Check
                  className="text-primary shrink-0 size-5"
                  aria-hidden="true"
                />
              </button>
              <button type="button">
                <Wind
                  className="text-muted-foreground shrink-0 size-5"
                  aria-hidden="true"
                />
                <span className="font-medium text-sm flex-1">Gas / Bloating</span>
                <Check
                  className="text-primary hidden shrink-0 size-5"
                  aria-hidden="true"
                />
              </button>
            </CardContent>
          </Card>
          <Card className="shadow-[0px_1px_3px_rgba(0,_0,_0,_0.1),_0px_1px_2px_-1px_rgba(0,_0,_0,_0.1)] rounded-xl bg-card border-border pt-4 pr-4 pb-4 pl-4 gap-4">
            <CardHeader className="pt-0 pr-0 pb-0 pl-0 gap-3">
              <div className="flex items-start gap-3">
                <div className="rounded-lg bg-secondary text-secondary-foreground flex justify-center items-center shrink-0 size-10">
                  <Moon className="size-5" aria-hidden="true" />
                </div>
                <div className="flex-1 min-w-0">
                  <CardTitle className="text-base leading-tight">
                    Sleep Quality / नींद
                  </CardTitle>
                  <div className="font-medium uppercase text-muted-foreground text-xs tracking-wider mt-1">
                    Nidra
                  </div>
                </div>
              </div>
            </CardHeader>
            <CardContent className="grid pt-0 pr-0 pb-0 pl-0 gap-2">
              <button type="button">
                <CircleCheck aria-hidden="true" />
                <span className="font-medium text-sm flex-1">
                  Sound uninterrupted
                </span>
                <Check
                  className="text-green-600 shrink-0 size-5"
                  aria-hidden="true"
                />
              </button>
              <button type="button">
                <CloudMoon
                  className="text-muted-foreground shrink-0 size-5"
                  aria-hidden="true"
                />
                <span className="font-medium text-sm flex-1">Disturbed</span>
                <Check
                  className="text-primary hidden shrink-0 size-5"
                  aria-hidden="true"
                />
              </button>
              <button type="button">
                <Clock3
                  className="text-muted-foreground shrink-0 size-5"
                  aria-hidden="true"
                />
                <span className="font-medium text-sm flex-1">
                  Difficulty sleeping / Insomnia
                </span>
                <Check
                  className="text-primary hidden shrink-0 size-5"
                  aria-hidden="true"
                />
              </button>
            </CardContent>
          </Card>
          <Card className="shadow-[0px_1px_3px_rgba(0,_0,_0,_0.1),_0px_1px_2px_-1px_rgba(0,_0,_0,_0.1)] rounded-xl bg-card border-border pt-4 pr-4 pb-4 pl-4 gap-4">
            <CardHeader className="pt-0 pr-0 pb-0 pl-0 gap-3">
              <div className="flex items-start gap-3">
                <div className="rounded-lg bg-secondary text-secondary-foreground flex justify-center items-center shrink-0 size-10">
                  <ThermometerSun className="size-5" aria-hidden="true" />
                </div>
                <div className="flex-1 min-w-0">
                  <CardTitle className="text-base leading-tight">
                    Weather Preference / मौसम पसंद
                  </CardTitle>
                  <div className="font-medium uppercase text-muted-foreground text-xs tracking-wider mt-1">
                    Satmya
                  </div>
                </div>
              </div>
            </CardHeader>
            <CardContent className="grid pt-0 pr-0 pb-0 pl-0 gap-2">
              <button type="button">
                <Snowflake
                  className="text-muted-foreground shrink-0 size-5"
                  aria-hidden="true"
                />
                <span className="font-medium text-sm flex-1">
                  Sensitive to cold
                </span>
                <Check
                  className="text-primary hidden shrink-0 size-5"
                  aria-hidden="true"
                />
              </button>
              <button type="button">
                <Sun
                  className="text-muted-foreground shrink-0 size-5"
                  aria-hidden="true"
                />
                <span className="font-medium text-sm flex-1">
                  Sensitive to heat
                </span>
                <Check
                  className="text-primary shrink-0 size-5"
                  aria-hidden="true"
                />
              </button>
              <button type="button">
                <CloudSun
                  className="text-muted-foreground shrink-0 size-5"
                  aria-hidden="true"
                />
                <span className="font-medium text-sm flex-1">Neutral</span>
                <Check
                  className="text-primary hidden shrink-0 size-5"
                  aria-hidden="true"
                />
              </button>
            </CardContent>
          </Card>
        </div>
      </main>
      <div className="bg-background border-x-border border-t border-t-border border-b-border flex pt-4 pr-4 pb-4 pl-4 items-center gap-3 w-full">
        <Button
          variant="outline"
          className="font-semibold rounded-lg text-sm flex-1 h-12"
        >
          Previous
        </Button>
        <Button className="font-semibold rounded-lg bg-primary text-primary-foreground text-sm flex-1 h-12">
          Continue / आगे बढ़ें
        </Button>
      </div>
    </div>;
    
  );
};

export default Screen04_AyushProfile;
