import React from 'react';
import {
  CircleDashed,
  Landmark,
  Accessibility,
  QrCode,
  ContactRound,
  CircleCheck,
  ArrowRight,
  Mic,
  ShieldCheck,
  Camera,
  Upload,
  FileText,
  Clock,
  User,
  HeartPulse,
  Flame,
  Moon,
  ThermometerSun,
  ChevronRight,
  PhoneCall
} from 'lucide-react';

/**
 * Live OPD Queue Token & Consultation Status
 * Generated by Flowstep AI for SwasthyaSaathi Android Mobile App
 * Screen ID: 98a8a6ac-35e4-4be8-865e-a9718725e06e
 */
export const Screen07_OpdTokenQueue: React.FC = () => {
  return (
    <!-- screenType: "mobile_android" width: "360" height: "780" name: "Screen 7" colorTheme: "orange" screenId: "98a8a6ac-35e4-4be8-865e-a9718725e06e" -->
    <div className="bg-background text-foreground w-full h-fit">
      <header className="bg-primary text-primary-foreground border-b border-b-primary/30 w-full">
        <div className="flex pr-4 pl-4 items-center gap-3 min-h-16">
          <div className="flex items-center flex-1 gap-3 min-w-0">
            <div
              className="rounded-full border-t-2 border-t-primary-foreground/80 border-r-2 border-r-primary-foreground/80 border-b-2 border-b-primary-foreground/80 border-l-2 border-l-primary-foreground/80 flex justify-center items-center shrink-0 size-10"
              aria-label="Ashok Chakra emblem"
            >
              <CircleDashed className="size-7" aria-hidden="true" />
            </div>
            <div className="min-w-0">
              <div className="font-semibold text-ellipsis whitespace-nowrap text-base tracking-tight overflow-hidden">
                SwasthyaSaathi
              </div>
              <div className="whitespace-nowrap text-primary-foreground/80 text-xs leading-tight">
                Health Companion / स्वास्थ्य साथी
              </div>
            </div>
          </div>
          <div className="flex items-center shrink-0 gap-2">
            <div
              className="rounded-lg bg-accent text-accent-foreground flex pt-1.5 pr-2 pb-1.5 pl-2 items-center gap-1.5 max-w-32"
              aria-label="Government / AYUSH Hospital"
            >
              <Landmark className="shrink-0 size-4" aria-hidden="true" />
              <span className="font-semibold text-[10px] leading-tight">
                Government / AYUSH Hospital
              </span>
            </div>
            <button
              type="button"
              className="transition-colors rounded-full text-primary-foreground flex justify-center items-center shrink-0 size-12"
              aria-label="Help and accessibility"
            >
              <Accessibility className="size-6" aria-hidden="true" />
            </button>
          </div>
        </div>
      </header>
      <main className="flex pt-4 pr-4 pb-4 pl-4 flex-col gap-4">
        <div
          className="rounded-lg bg-emerald-50 text-emerald-800 border-t border-t-emerald-200 border-r border-r-emerald-200 border-b border-b-emerald-200 border-l border-l-emerald-200 flex pt-4 pr-4 pb-4 pl-4 items-center gap-3"
          role="status"
        >
          <CheckCircle2
            className="text-emerald-600 shrink-0 size-5"
            aria-hidden="true"
          />
          <div className="font-medium text-sm">
            Intake submitted successfully / जानकारी भेज दी गई
          </div>
        </div>
        <section
          className="shadow-[0px_6px_12px_-4px_rgba(0,_0,_0,_0.16)] rounded-lg bg-card border-t border-t-border border-r border-r-border border-b border-b-border border-l border-l-border flex pt-6 pr-6 pb-6 pl-6 flex-col gap-4"
          aria-label="OPD token"
        >
          <div className="text-center flex flex-col gap-1">
            <div className="font-semibold text-muted-foreground text-xs tracking-widest">
              YOUR OPD TOKEN / आपका टोकन
            </div>
            <div className="font-bold text-foreground text-4xl tracking-tight">
              OPD-A42
            </div>
          </div>
          <div className="bg-border w-full h-px" />
          <div className="text-center flex justify-center items-center gap-8">
            <div className="flex flex-col gap-1">
              <div className="font-bold text-foreground text-2xl">12 mins</div>
              <div className="text-muted-foreground text-xs">Estimated wait</div>
            </div>
            <div className="bg-border w-px h-10" />
            <div className="flex flex-col gap-1">
              <div className="font-bold text-foreground text-2xl">3</div>
              <div className="text-muted-foreground text-xs">patients ahead</div>
            </div>
          </div>
          <div className="rounded-lg bg-muted flex pt-4 pr-4 pb-4 pl-4 flex-col gap-1">
            <div className="font-semibold text-foreground text-base">
              Dr. Ayush Sharma
            </div>
            <div className="text-muted-foreground text-sm">MD Ayurveda</div>
          </div>
          <div className="font-medium text-foreground text-sm flex items-center gap-2">
            <MapPin className="text-primary shrink-0 size-4" aria-hidden="true" />
            <span>OPD Room 104 • Ground Floor</span>
          </div>
        </section>
        <section className="flex flex-col gap-4" aria-label="Live status">
          <div className="flex justify-between items-center">
            <h2 className="font-semibold text-base">
              Live status / वर्तमान स्थिति
            </h2>
            <span className="text-muted-foreground text-xs">
              Last updated just now
            </span>
          </div>
          <div className="flex items-start">
            <div className="text-center flex flex-col items-center flex-1 gap-2 min-w-0">
              <div className="rounded-full bg-emerald-600 text-white flex justify-center items-center size-8">
                <Check className="size-4" aria-hidden="true" />
              </div>
              <div className="font-semibold text-emerald-700 text-[11px] leading-tight">
                Intake Submitted
              </div>
            </div>
            <div className="bg-emerald-500 mt-4 flex-1 h-0.5" />
            <div className="text-center flex flex-col items-center flex-1 gap-2 min-w-0">
              <div className="rounded-full bg-primary text-primary-foreground flex justify-center items-center size-8">
                <span className="animate-pulse rounded-full bg-primary-foreground size-2.5" />
              </div>
              <div className="font-semibold text-primary text-[11px] leading-tight">
                Doctor Reviewing Case Sheet
              </div>
            </div>
            <div className="bg-border mt-4 flex-1 h-0.5" />
            <div className="text-center flex flex-col items-center flex-1 gap-2 min-w-0">
              <div className="rounded-full bg-muted border-t-2 border-t-border border-r-2 border-r-border border-b-2 border-b-border border-l-2 border-l-border size-8" />
              <div className="font-semibold text-muted-foreground text-[11px] leading-tight">
                Ready for Consultation
              </div>
            </div>
          </div>
        </section>
        <div className="flex pt-2 flex-col gap-2">
          <button
            type="button"
            className="font-semibold transition-colors rounded-lg bg-background text-foreground text-sm border-t border-t-border border-r border-r-border border-b border-b-border border-l border-l-border flex pr-4 pl-4 justify-center items-center gap-2 w-full h-12"
          >
            <Download className="size-4" aria-hidden="true" />
            <span>Download Token Slip (PDF)</span>
          </button>
          <button
            type="button"
            className="font-semibold transition-colors rounded-lg bg-primary text-primary-foreground text-sm flex pr-4 pl-4 justify-center items-center gap-2 w-full h-12"
          >
            <Phone className="size-4" aria-hidden="true" />
            <span>Emergency Assistance</span>
          </button>
        </div>
        <p className="text-center text-muted-foreground text-xs">
          Please stay near the OPD waiting area.
        </p>
      </main>
    </div>;
    
  );
};

export default Screen07_OpdTokenQueue;
